

spring:
  datasource:
    url: jdbc:mysql://rm-wz9515p648o5t6is9o.mysql.rds.aliyuncs.com:3306/test
    username: devops
    password: devOps!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 9002

